name: Package Ignited Skin

on:
  push:
    branches: ["main"]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow releases
permissions:
  contents: write

jobs:
  package:
    name: Create Skin Package
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install imagemagick

      - name: Generate PDF skin image
        run: |
          BUTTONS=("save" "swap" "menu" "fast")
          for BTN in ${BUTTONS}; do
            convert ./assets/${BTN}.png -alpha set -background none -channel A -evaluate multiply 0.2 +channel ${BTN}_a.png
          done

          magick -size 2688x1242 xc:none \
            save_a.png  -geometry    +45+45  -composite \
            swap_a.png  -geometry  +2155+45  -composite \
            menu_a.png  -geometry   +45+643  -composite \
            fast_a.png  -geometry +2155+849  -composite \
            insiDS.pdf

      - name: Create skin archive
        run: |
          zip insiDS.ignitedskin info.json insiDS.pdf README.md LICENSE

      - name: Release skin
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: latest
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            insiDS.ignitedskin
