name: Package Ignited Skin

on:
    # push:
    #     branches: ["main"]

    # Allows running this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    package:
        name: Create Skin Package and Upload as Artifact
        runs-on: macos-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  brew update
                  brew install imagemagick

            - name: Convert .xcf to .pdf
              run: convert -alpha on -background none -layers merge insiDS.xcf insiDS.pdf

            - name: Create .ignitedskin package
              run: zip insiDS.ignitedskin info.json insiDS.pdf insiDS.xcf README.md LICENSE

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: insiDS Skin
                  path: insiDS.ignitedskin
