name: Package insiDS Skin

on:
  push:
    branches: ["main"]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow releases
permissions:
  contents: write

jobs:
  package:
    name: Create and Release Skin Packages
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: imagemagick

      - name: Generate rounded button PNGs
        run: |
          BUTTONS=("save" "load" "swap" "menu" "fast")
          for BTN in ${BUTTONS}; do
            magick ./assets/${BTN}.png  ./assets/masks/${BTN}.png  \
              -compose ChangeMask  -composite  ./assets/${BTN}.png
          done

      - name: Generate PDF skin image for Ignited
        run: |
          magick -size 2688x1242 xc:none \
            ./assets/save.png  -geometry    +45+45  -composite \
            ./assets/menu.png  -geometry   +45+643  -composite \
            ./assets/swap.png  -geometry  +2155+45  -composite \
            ./assets/fast.png  -geometry +2155+849  -composite \
            insiDS.pdf

      - name: Create skin package for Ignited
        run: |
          zip insiDS.ignitedskin info.json insiDS.pdf README.md LICENSE

      - name: Generate PDF skin image for Delta
        run: |
          magick -size 2688x1242 xc:none \
            ./assets/save.png  -geometry    +45+45  -composite \
            ./assets/menu.png  -geometry   +45+643  -composite \
            ./assets/load.png  -geometry  +2155+45  -composite \
            ./assets/fast.png  -geometry +2155+849  -composite \
            insiDS.pdf

      - name: Create skin packages for Delta
        run: |
          zip insiDS.deltaskin insiDS.pdf README.md LICENSE
          cp insiDS.deltaskin insiDS-alt.deltaskin
          (cd delta/main; zip -ur ../../insiDS.deltaskin ./)
          (cd delta/alt; zip -ur ../../insiDS-alt.deltaskin ./)

      - name: Release skin
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: latest
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            insiDS.ignitedskin
            insiDS.deltaskin
            insiDS-alt.deltaskin
