name: Package Ignited Skin

on:
  push:
    branches: ["main"]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow releases
permissions:
  contents: write

jobs:
  package:
    name: Create Skin Package
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install imagemagick

      - name: Generate PDF skin image
        env:
          BTN_ALPHA: 0.2
        run: |
          magick -size 2688x1242 xc:none \
            ./assets/save.png  -geometry    +45+45  -composite \
            ./assets/swap.png  -geometry  +2155+45  -composite \
            ./assets/menu.png  -geometry   +45+643  -composite \
            ./assets/fast.png  -geometry +2155+849  -composite \
            -alpha set -background none -channel A -evaluate multiply ${BTN_ALPHA} +channel \
            insiDS.pdf

      - name: Create skin archive
        run: |
          zip insiDS.ignitedskin info.json insiDS.pdf README.md LICENSE

      - name: Release skin
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: latest
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            insiDS.ignitedskin
